number01 = int(input("please enter first number : "))
number02 = int(input("please enter first number : "))
number03 = int(input("please enter first number : "))
maximum = max(number01, number02, number03)
print(maximum)